config/routes.rb
Blogger::Application.routes.draw do

  resources :pruebalocas

  resources :tests

  resources :groups

  devise_for :users, :controllers => {:registrations => "registrations"}

  match '/users/show_login' => 'users#show_login'
  
  root :to => 'users#index'

  resources :tags

  resources :users do
      resources :posts do
         resources :comments
      end
      get 'show_public'
      get 'follow'
      get 'unfollow'
  end

  match '/search/index' => 'search#index' 
  match '/search/search_by_fields' => 'search#search_by_fields', :via=>:post

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :post_id
 
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.where(:post_id => params[:post_id])
    @post = Post.find(params[:post_id])
    @user= User.find(params[:user_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])
    @post= Post.find(params[:post_id])
    @user= User.find(params[:user_id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    @user= User.find(params[:user_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    @user= User.find(params[:user_id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    @post = Post.find(params[:post_id])
    @user= User.find(params[:user_id])
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@user,@post], notice: 'Comment was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    @user= User.find(params[:user_id])
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to [@user,@post], notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    @post = Post.find(params[:post_id])
    @user= User.find(params[:user_id])
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@user,@post,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Back', user_post_comments_path {[@user,@post]} %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>User</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user_id %></td>
    <td><%= comment.content %></td>
    <td><%= link_to 'Show', user_post_comment_path(@user,@post,comment)%></td>
    <td><%= link_to 'Edit', edit_user_post_comment_path(@user, @post, comment) %></td>
    <td><%= link_to 'Destroy', [@user,@post,comment], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_user_post_comment_path {[@user,@post]}%>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', user_post_comments_path {[@user,@post]} %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>