config/routes.rb
Blogger::Application.routes.draw do

  resources :pruebalocas

  resources :tests

  resources :groups

  devise_for :users, :controllers => {:registrations => "registrations"}

  match '/users/show_login' => 'users#show_login'
  
  root :to => 'users#index'

  resources :tags

  resources :users do
      resources :posts do
         resources :comments
      end
      get 'show_public'
      get 'follow'
      get 'unfollow'
  end

  match '/search/index' => 'search#index' 
  match '/search/search_by_fields' => 'search#search_by_fields', :via=>:post

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
   
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :birthdate, :image, :lastname, :role

  has_many :posts
  has_many :comments
  has_and_belongs_to_many :group
  has_many :group
  
  validates_presence_of :lastname, :name
	validates :email, :presence => true
 	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
 	validates_uniqueness_of :email
 	validates :password, :presence => true, :length => {:within => 6..40}, :on =>:create
 	validates_confirmation_of :password  

  acts_as_followable
  acts_as_follower
  def get_followed
    result = []
    self.follows.each do |f|
        result << {:followable_id => f.followable_id, :followable_name => User.find(f.followable_id).name}
    end
    return result
  end

def get_followed_id
    result = []
    self.follows.each do |f|
        result << f.followable_id
    end
    return result
  end

  def get_not_followed
    total = []
    result = []
    User.all.each do |u|
      total << u.id
    end
    total = total-self.get_followed_id-[self.id]
    total.each do |f|
        result << {:not_followable_id => f, :not_followable_name => User.find(f).name}
    end
    return result
  end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
 #before_filter :require_login, :only => [:index, :update]
 #before_filter :require_auth, :only => [:show, :index, :update]
  load_and_authorize_resource
  before_filter :authenticate_user!
  

  def require_login
    if(session[:user_id] == nil) 
      redirect_to users_show_login_path
    end
  end

  def require_auth    
    if(params[:user_id] == nil)
        user_id = params[:id]
    else
        user_id = params[:user_id]
    end

    unless(session[:user_id].to_s == user_id) 
      @user = User.find(user_id)      
      redirect_to user_show_public_path @user     
    end
  end
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @post = Post.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    #user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])  
    image =  params[:user][:image]
    
    if(image)
      # save image
      directory = "app/assets/images/"
      path = File.join(directory, image.original_filename)
      File.open(path, "wb") { |f| f.write(image.read) }

      @user.image = image.original_filename
    end
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def show_login
    
    respond_to do |format|
      if(session[:user_id])  
        @user = User.find_by_id(session[:user_id])
        format.html { redirect_to @user, notice: "Already logued." }         
      else
        #format.html { render :layout=> "not_logged" }# index.html.erb
        format.html { redirect_to new_user_session_path}                 
      end
    end
  end

  def authenticate
    @user = User.find_by_email_and_password(params[:email], params[:password])    
    respond_to do |format|
      if (@user)
        session[:user_id] = @user.id
        User.find(session[:user_id])
        format.html { redirect_to @user, notice: "User was successfully logued." }        
      else        
        format.html do 
          flash[:notice] = "Fail to login #{params[:email]}"
          redirect_to(:controller => "users", :action => "show_login")
        end
      end
    end
  end

  def logout  
    respond_to do |format|
      reset_session
      
      format.html {redirect_to(:controller => "users", :action => "show_login") }
    end
  end

  def show_public
    @user = User.find(params[:user_id])
    @can_follow = !(current_user.following?(@user))

    respond_to do |format|
      format.html 
    end
  end

  def follow
    user = User.find(params[:user_id])
    current_user.follow(user)
    respond_to do |format|
      format.html { redirect_to current_user, notice: "Follow User: #{user.name}" }         
    end
  end


  def unfollow
    user = User.find(params[:user_id])
    current_user.stop_following(user)
    respond_to do |format|
      format.html { redirect_to current_user, notice: "Unfollow User: #{user.name}" }         
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, :html => { :multipart => true }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br />
    <%= f.text_field :birthdate %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form_new_post.html.haml
= form_for([@user,@post], :html => { :multipart => true }) do |f|
  - if @post.errors.any?
    %div#error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li
            = msg
  - f.hidden_field :user_id, {:value => @post.user_id}
  %div.field
    = f.label t('posts.title')
    = f.text_field :title
    = f.label t('posts.content')
    = f.text_area :content
    = label_tag t('posts.tag')
    = text_field_tag :tag
    = label_tag t('posts.image')
    = f.file_field :image
  %div.actions
    = f.submit t('posts.create_post')

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lastname</th>
    <th>Mail</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.lastname %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Registration</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.haml
%h1.inside_title
  = @user.name
  's home
%br
%table
  %tr
    %td
    %h2 
      = t('posts.my_posts')
  %tr
    %td
      - @user.posts.reverse.each do |post|
        %div.box_content.post_content
          = link_to post.title, user_post_path(@user,post)
          %br
          %br
          = image_tag post.image.url(:thumb)
          = post.content
          %h6
            = t('posts.created_time')
            = post.created_at
            = link_to 'Delete', [@user,post], confirm: 'Are you sure?', method: :delete
%h1.inside_title
  = t('posts.create_new_post')
%br
= render 'form_new_post'

app/views/users/show_login.html.erb
<h1 class="inside_title">Login</h1>
<%= form_tag("/users/authenticate", :method => "get") do%>
  <div class="field">
    <%= label_tag(:mail, "E-Mail:") %>
    <%= text_field_tag(:mail) %>  
  </div>
  <div class="field">
   <%= label_tag(:password, "Password:") %>
    <%= password_field_tag(:password) %>
  </div>
  <div class="actions">
    <%= submit_tag("Login") %>
    <%= link_to 'New User', new_user_path %>
  </div>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>

app/views/users/show_public.html.erb
<p>
  <b>Name:</b>
  <%= @user.name %>
  <% if (@can_follow)%>
    <div class ="link"><%= link_to 'Follow', user_follow_path %></div>
  <%else%>
    <div class ="link"><%= link_to 'Unfollow', user_unfollow_path %></div>
  <%end%>
</p>

<p>
  <b>Mail:</b>
  <%= @user.email %>
</p>
<p>
  <%= image_tag @user.image %>
</p>

<p> ----------------------------------------------------------- </p> <br>
<table>
  <tr>
    <th>Name</th>
    <th>Message</th>
    <th>Date</th>
    <th></th>
  </tr>

<% @user.posts.each do |post| %>
  <tr>
    <td><%= @user.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', user_post_path(@user,post) %></td>
  </tr>
<% end %>
</table>

<p> ----------------------------------------------------------- </p> <br>