config/routes.rb
Blogger::Application.routes.draw do

  resources :pruebalocas

  resources :tests

  resources :groups

  devise_for :users, :controllers => {:registrations => "registrations"}

  match '/users/show_login' => 'users#show_login'
  
  root :to => 'users#index'

  resources :tags

  resources :users do
      resources :posts do
         resources :comments
      end
      get 'show_public'
      get 'follow'
      get 'unfollow'
  end

  match '/search/index' => 'search#index' 
  match '/search/search_by_fields' => 'search#search_by_fields', :via=>:post

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :image, :id, :created_at, :updated_at, :image_file_name, :image_content_type, :image_file_size, :image_updated_at
  belongs_to :user
  belongs_to :group
  has_many :comments

  scope :by_tag, lambda { |tag| Post.tagged_with(tag) if !(tag.empty?)}
	scope :by_keyword, lambda { |keyword| {:conditions=>['content LIKE ?', '%'+keyword+'%']} if !(keyword.empty?)}
	scope :by_created, lambda { |created| {:conditions=>['posts.created_at LIKE ?', '%'+created+'%']} if !(created.empty?)}
  
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  acts_as_taggable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user! 
  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
    @user= User.find(params[:user_id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @user= User.find(params[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @user= User.find(params[:user_id])
    @post = Post.find(params[:id])
     respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id = (params[:user_id])
    @user = User.find(params[:user_id])
    tags = params[:tag].split(', ')
    tags.each do |t|
      t.strip!
      @post.tag_list.add(t)
    end
    respond_to do |format|
      if @post.save
        format.html { redirect_to @user, notice: 'Post was successfully created.' }
        format.json { render json: @user, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end



  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    @user= User.find(params[:user_id])
    @post.user_id = (params[:user_id])
    tags = params[:tag].split(', ')
    tags.each do |t|
      @post.tag_list.add(t)
    end
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to [@user,@post], notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE users/{id}/posts/1
  # DELETE users/{id}/posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @user= User.find(params[:user_id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to user_posts_url @user }
      format.json { head :no_content }
    end
  end
end
    

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for([@user,@post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% f.hidden_field :user_id, {:value => @post.user_id} %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= label_tag :tag %>
    <%= text_field_tag :tag, @post.tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_posts_path {@user} %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>User</th>
    <th>Content</th>
    <th>Title</th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.user_id %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', user_post_path(@user,post) %></td>
    <td><%= link_to 'Edit', edit_user_post_path(@user,post) %></td>
    <td><%= link_to 'Destroy', [@user,post], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_user_post_path {(@user)}%>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_posts_path {@user} %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @post.user_id %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>
<%= image_tag @post.image.url(:medium) %>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
<p>
  <b>Tags:</b>
    <% tags =@post.tag_counts.order() %>
    <% tags.uniq.each do |t| %>
      <%= link_to t.name, tag_path(t.id), :class => "linkTag"%>
    <% end%>
</p>


<% if(current_user.id == @post.user_id) %>
  <%= link_to 'Edit', edit_user_post_path(current_user.id,@post) %> | 
<% end%>  
<%= link_to 'Back', user_path(current_user) %>
<p>----------------------------------<%=t('comments.new_comment')%>-----------------------------</p>
<p>------------------------------------------------------------------------------------</p>
<%= form_for([@user,@post,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit t('comments.create_comment') %>
  </div>
<% end %><br><br><br>
<p>------------------------------------Comentarios----------------------------------</p>
<p>------------------------------------------------------------------------------------</p>
<table>
  <tr>
    <th>User</th>
    <th>Content</th>
    <th></th>
    <th></th>
  </tr>

<% @post.comments.reverse.each do |comment| %>
  <tr>
    <td><%= comment.user_id %></td>
    <td><%= comment.content %></td>
    <td>
        <%= 
        if(current_user.id==comment.user_id) 
              link_to 'Edit', edit_user_post_comment_path(@user, @post, comment) 
        end
        %>
    </td>
    <td>
      <%= 
      if(current_user.id==comment.user_id)
        link_to 'Destroy', [@user,@post,comment], confirm: t('posts.confirm'), method: :delete
      else
        if (current_user.id==comment.post_id)
          link_to 'Destroy', [@user,@post,comment], confirm: t('posts.confirm'), method: :delete
        end
      end
      %>
    </td>
  </tr>
<% end %>
</table>