config/routes.rb
Blogger::Application.routes.draw do

  resources :pruebalocas

  resources :tests

  resources :groups

  devise_for :users, :controllers => {:registrations => "registrations"}

  match '/users/show_login' => 'users#show_login'
  
  root :to => 'users#index'

  resources :tags

  resources :users do
      resources :posts do
         resources :comments
      end
      get 'show_public'
      get 'follow'
      get 'unfollow'
  end

  match '/search/index' => 'search#index' 
  match '/search/search_by_fields' => 'search#search_by_fields', :via=>:post

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%=javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>  
</head>
<body>  
  <div class = "content">
    <div class = "header">

      <% if (user_signed_in?) %>
        <div class ="link"><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></td></div>
      <%end%>

      <h1> Blogger</h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>
    <div class = "info" id="info">
    <%= yield %>
    </div>



    <div class = "sidebar" id="sidebar">
      <h1 class = "inside_title">My stuff</h1>

      <% if (user_signed_in?) %>
      <div class="tag_content box_content">
        <div class="link"><%= link_to 'Edit my account', edit_user_registration_path %></div><br>
        <%= link_to image_tag(current_user.image), user_path(current_user)%>
        </div>
     </td>
      <br>

      <div class="tag_content box_content">
      <h1 class = "inside_title">Followed users</h1>
      <% current_user.get_followed.each do |f| %>
        <div class ="link"><%= link_to f[:followable_name], user_show_public_path(f[:followable_id]) %></div>
      <% end%>
      </div>

      <div class="tag_content box_content">
      <h1 class = "inside_title">Suggested users</h1>
      <% current_user.get_not_followed.each do |f| %>
        <div class ="link"><%= link_to f[:not_followable_name], user_show_public_path(f[:not_followable_id]) %></div>
      <% end%>
      </div>

      <div class="tag_content box_content">
      <h1 class = "inside_title">My tags</h1>
        <% tags =current_user.posts.tag_counts.order() %>
        <% tags.uniq.each do |t| %>
          <%= link_to t.name, tag_path(t.id), :class => "linkTag"%>
        <% end%>
      </div>
      <%end%>

    </div>
    <div class = "footer">
      rails blogger -majo.adrian.fede.fer- 2012
    </div>
  </div>
</body>
</html>

app/views/layouts/not_logged.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%=javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>  
</head>
<body>
  
  <div class = "content">
    <div class = "header">
      <% if (user_signed_in?) %>
        <div class ="link"><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></td></div>
      <% else %>
        <div class ="link"><%= link_to 'Login', new_user_session_path %></td></div>
      <%end%>
      <div class ="link"><%= link_to 'Search', search_index_path %></td> </div>
    </div>
    <div class = "info" id="info">
    <%= yield %>
    </div>

    <div class = "sidebar" id="sidebar">
      <h1 class = "inside_title">My stuff</h1>

      <% if (user_signed_in?) %>
      <div class="tag_content box_content">
        <div class="link"><%= link_to 'Edit my account', edit_user_registration_path %></div><br>
        <%= link_to image_tag(current_user.image), user_path(current_user)%>
        </div>
     </td>
      <br>

      <div class="tag_content box_content">
      <h1 class = "inside_title">Followed users</h1>
      <% current_user.get_followed.each do |f| %>
        <div class ="link"><%= link_to f[:followable_name], user_show_public_path(f[:followable_id]) %></div>
      <% end%>
      </div>

      <div class="tag_content box_content">
      <h1 class = "inside_title">Suggested users</h1>
      <% current_user.get_not_followed.each do |f| %>
        <div class ="link"><%= link_to f[:not_followable_name], user_show_public_path(f[:not_followable_id]) %></div>
      <% end%>
      </div>

      <div class="tag_content box_content">
      <h1 class = "inside_title">My tags</h1>
        <% tags = current_user.posts.tag_counts.order() %>
        <% tags.uniq.each do |t| %>
          <%= link_to t.name, tag_path(t.id) %>
        <% end%>
      </div>
      <%end%>

    </div>


    
    <div class = "footer">
      rails blogger -majo.adrian.fede.fer- 2012
    </div>
  </div>
</body>
</html>